USE [master]
GO

/****** Object:  Database [SecureAuthenticate]    Script Date: 24/11/2025 2:18:00 AM ******/
CREATE DATABASE [SecureAuthenticate]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SecureAuthenticate', FILENAME = N'D:\MyDB_Data\SecureAuthenticate.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SecureAuthenticate_log', FILENAME = N'D:\MyDB_Log\SecureAuthenticate_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SecureAuthenticate].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SecureAuthenticate] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET ARITHABORT OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SecureAuthenticate] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SecureAuthenticate] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SecureAuthenticate] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SecureAuthenticate] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SecureAuthenticate] SET  MULTI_USER 
GO

ALTER DATABASE [SecureAuthenticate] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SecureAuthenticate] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SecureAuthenticate] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SecureAuthenticate] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SecureAuthenticate] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SecureAuthenticate] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [SecureAuthenticate] SET QUERY_STORE = ON
GO

ALTER DATABASE [SecureAuthenticate] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SecureAuthenticate] SET  READ_WRITE 
GO


